version: "3.8"

services:
  mcp_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
    ports:
      - "8000:8000"

  gradio_client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - mcp_server
    environment:
      - MCP_SERVER_URL=http://mcp_server:8000/sse
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "7860:7860"
